# Generated by Django 4.0.4 on 2022-05-22 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contactFormMessages',
            new_name='contactFormMessage',
        ),
    ]
