# Generated by Django 4.0.4 on 2022-05-25 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_quotation_specialofferleads'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='domain_name',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=40),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='hosting',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=40),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='technical_suport',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=40),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='web_design',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=40),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='web_development',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=40),
        ),
    ]
