# Generated by Django 4.0.4 on 2022-05-25 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_quotation_domain_name_alter_quotation_hosting_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='quotation_total',
            field=models.CharField(default=0, max_length=40),
        ),
    ]
