# Generated by Django 4.0.4 on 2022-05-26 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_quotation_seo'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='domain_name_value',
            field=models.CharField(default=0, max_length=40),
        ),
        migrations.AddField(
            model_name='quotation',
            name='hosting_value',
            field=models.CharField(default=0, max_length=40),
        ),
        migrations.AddField(
            model_name='quotation',
            name='seo_value',
            field=models.CharField(default=0, max_length=40),
        ),
        migrations.AddField(
            model_name='quotation',
            name='technical_suport_value',
            field=models.CharField(default=0, max_length=40),
        ),
        migrations.AddField(
            model_name='quotation',
            name='web_design_value',
            field=models.CharField(default=0, max_length=40),
        ),
        migrations.AddField(
            model_name='quotation',
            name='web_development_value',
            field=models.CharField(default=0, max_length=40),
        ),
    ]
