# Generated by Django 4.0.4 on 2022-06-30 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_quotation_domain_name_value_quotation_hosting_value_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('project_image', models.ImageField(upload_to='Projects Images')),
                ('started_on', models.DateField()),
                ('completed_on', models.DateField()),
                ('details', models.TextField(max_length=2500)),
            ],
        ),
        migrations.AlterField(
            model_name='quotation',
            name='website_type',
            field=models.CharField(choices=[('Basic Website', 'Basic Website'), ('Standard Website', 'Standard Website'), ('Advanced Website', 'Advanced Website')], default='Basic Website', max_length=40),
        ),
    ]
