# Generated by Django 4.0.4 on 2022-06-30 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_project_alter_quotation_website_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_image_mobile',
            field=models.ImageField(null=True, upload_to='Projects Images'),
        ),
    ]
