# Generated by Django 4.0.4 on 2022-07-03 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_project_project_image_mobile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='details',
        ),
        migrations.AddField(
            model_name='project',
            name='approach',
            field=models.TextField(max_length=2500, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='challenge',
            field=models.TextField(max_length=2500, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='introduction',
            field=models.TextField(max_length=2500, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='solution',
            field=models.TextField(max_length=2500, null=True),
        ),
    ]
