# Generated by Django 4.0.4 on 2022-07-03 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_rename_approach_project_details_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialofferleads',
            name='industry',
        ),
    ]
