# Generated by Django 4.0.4 on 2022-08-15 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_freewebsirelead_alter_project_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='freeWebsireLead',
            new_name='freeWebsiteLead',
        ),
    ]
