# Generated by Django 4.0.4 on 2022-09-02 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_rename_details_freewebsitelead_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialofferleads',
            name='whatsapp_number',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
