# Generated by Django 4.0.4 on 2022-09-02 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_specialofferleads_whatsapp_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialofferleads',
            name='whatsapp_number',
        ),
        migrations.AddField(
            model_name='freewebsitelead',
            name='whatsapp_number',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
