# Generated by Django 4.0.4 on 2022-09-13 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_freewebsitelead_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='country',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
