# Generated by Django 4.0.4 on 2022-09-13 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_quotation_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='domain_name',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='domain_name_value',
            field=models.CharField(default=0, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='hosting',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='hosting_value',
            field=models.CharField(default=0, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='quotation_total',
            field=models.CharField(default=0, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='seo',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='seo_value',
            field=models.CharField(default=0, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='technical_suport',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='technical_suport_value',
            field=models.CharField(default=0, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='web_design',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='web_design_value',
            field=models.CharField(default=0, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='web_development',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='web_development_value',
            field=models.CharField(default=0, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='website_type',
            field=models.CharField(choices=[('Basic Website', 'Basic Website'), ('Standard Website', 'Standard Website'), ('Advanced Website', 'Advanced Website')], default='Basic Website', max_length=40, null=True),
        ),
    ]
