# Generated by Django 4.0.4 on 2022-12-04 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_alter_quotation_domain_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(max_length=255, null=True, unique=True),
        ),
    ]
