# Generated by Django 4.0.4 on 2022-12-04 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_project_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quotation',
            old_name='first_name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='domain_name',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='domain_name_value',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='hosting',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='hosting_value',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='quotation_total',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='seo',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='seo_value',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='technical_suport',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='technical_suport_value',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='web_design',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='web_design_value',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='web_development',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='web_development_value',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='website_type',
        ),
    ]
